### ISSUE TITLE
Could not resolve dependencies for project com.amazonaws.flink.refarch

### ISSUE THREAD

**Issue by issnoe** [aws-samples/flink-stream-processing-refarch#1]
Hi i get this error on compile;
flink-taxi-stream-processor: Could not resolve dependencies for project com.amazonaws.flink.refarch:flink-taxi-stream-processor:jar:1.3: Failure to find org.apache.flink:flink-connector-kinesis_2.11:jar:1.5.2 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced

**Comment by sthm** [comment]
Hey,

I'm afraid, the Kinesis connector is not available from Maven central. You need to build it yourself. One of the CloudFormation templates that is included in this repository will build the connector and upload it to S3, but you can also manually execute the steps on your local machine.

https://github.com/aws-samples/flink-stream-processing-refarch/blob/master/cfn-templates/flink-refarch-build-artifacts.yml#L153

Hope that helps.
